### ISSUE TITLE
Callback de Erros 

### ISSUE THREAD

**Issue by yaansz** [Softawii/curupira#6]
Quando não é possível executar a função retornar um callback (slash, exception)

**Comment by FerroEduardo** [comment]
Ter uma classe ExceptionResolver/Handler que recebe exceptions lançadas e lida com elas baseado na classe da exceção

[exception-handling-for-rest-with-spring](https://www.baeldung.com/exception-handling-for-rest-with-spring#5-custom-handlerexceptionresolver)
